spring:
  data:
    cassandra:
      keyspace-name: main
      username: MOhwvIZvtpIhJxEdfLyZuNIx
      password: u.l_zc2851ONLlESZBUOJxqg-Hf7fTOa-7A3o5QZbE7Z0bhwTPA,wpRzsWdMb8OTYg8Rw6iXMoLPgfN6QK_qCN,+ZezLx050L,Ph9kO99,z3+.MdZ.CrPGiOb19p1,+U
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

spring.main.allow-circular-references: true
        
datastax.astra:
  secure-connect-bundle: secure-connect.zip
  
astra.db:
  id: cdc492f9-8687-491e-aa8f-72aa38bdf489
  region: asia-south1
  keyspace: main
  application.token: AstraCS:MOhwvIZvtpIhJxEdfLyZuNIx:810769f59c6a9949c12e07f27d01fc86144d2f39df60b3426e83421536eabca6
              
      
      


# 